### ISSUE TITLE
Getting Started Documenation Issue - New-DeploymentPackage

### ISSUE THREAD

**Issue by JasonRowe** [powerdeploy/Powerdeploy#6]
I noticed the example on the [Getting Started] (https://github.com/powerdeploy/Powerdeploy/wiki/Getting-Started) page

 `New-DeploymentPackage c:\temp\package ShowConfiguration 1.2.3 c:\temp` 

shows that the parameter OutputDirectoryPath is positional but it is not. Should we update the function or update the wiki or am I missing something?

**Comment by jasonmueller** [comment]
I think it should remain positional (as it _should_ be optional, but it's not currently) and having so many positional arguments can get confusing.  I fixed the documentation but will open another issue to make the parameter optional.
